### ISSUE TITLE
Allow to set Browsersync options

### ISSUE THREAD

**Issue by koya-iwasaki** [ktsn/houl#31]
Hi!
I would like to set Browsersync options.
For example [startPath](https://www.browsersync.io/docs/options#option-startPath).
Could you add Browsersync options to Houl?

**Comment by ktsn** [comment]
Currently, I don't have a plan to expose the Browsersync options because it may breaks the core Houl feature (such as dynamic transformation of assets).
Maybe I will expose them as a Houl options like `--port`

**Comment by koya-iwasaki** [comment]
I agree to that.
I will use a `--base-path` option.
Thanks a lot.
